version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres:12
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend
  
  gazello:
    container_name: gazello
    build:
      context: .
      target: development
    
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run start:dev

    depends_on:
      - db
    
    networks:
      - backend

networks:
  backend:
volumes:
  pgdata: